### ISSUE TITLE
KeyboardInfo attributes not accessible due to internal protection level

### ISSUE THREAD

**Issue by GrandLarseny** [BottleRocketStudios/iOS-KeyboardSupport#30]
When trying to access the animation duration from the keyboardInfo object in the keyboardDidShow function, I received the following error: 

`'animationDuration' is inaccessible due to 'internal' protection level`

**Comment by earlgaspard** [comment]
This is a good catch. KeyboardInfo was recently changed to public but its properties were over looked. Going to fix in the next release.

**Comment by earlgaspard** [comment]
Fixed in 2.0.1
