### ISSUE TITLE
Protocol functions declared as optional still required

### ISSUE THREAD

**Issue by GrandLarseny** [BottleRocketStudios/iOS-KeyboardSupport#31]
It looks like the implementations of the functions in the protocol extension need to be set to `public` in order for them to be truly optional.

In particular, I'm referencing the functions:

`func keyboardWillShow(keyboardInfo: KeyboardInfo)`
`func keyboardWillHide(keyboardInfo: KeyboardInfo)`

**Comment by earlgaspard** [comment]
Another good finding. Going to fix in the next release.

**Comment by earlgaspard** [comment]
Fixed in 2.0.1
