### ISSUE TITLE
Reorganize Swift files

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-KeyboardSupport#37]
This mainly applies to `KeyboardRespondable.swift` as it encapsulates 3 concepts - `KeyboardRespondable`, `KeyboardDismissable`, and `KeyboardScrollable`. There are also a couple of `UIView` extensions sprinkled in there as well. We should split these up across separate Swift files for better clarity. We should do this after all outstanding PRs are merged (currently just #36).

**Comment by earlgaspard** [comment]
I am for splitting these files.
@tylermilner what do you think about removing the KeyboardRespondable protocol? My current project does not implement it in favor of conforming to KeyboardDismissable and KeyboardScrollable separately because setupKeyboardRespondable() does not give any insight into what that function is suppose to do.

**Comment by tylermilner** [comment]
@earlgaspard I am for removing `KeyboardRespondable` if you think it's a good idea. The only reason it exists is for convenience (consolidating 2 protocol conformances into 1, reducing the amount of boilerplate functions needed to be called, etc.).

**Comment by earlgaspard** [comment]
`KeyboardRespondable` introduces a function called `setupKeyboardRespondable()` that calls `setupKeyboardDismissalView()` from `KeyboardDismissable`. When conforming to `KeyboardRespondable`, one is able to call  `setupKeyboardRespondable()` and/or`setupKeyboardDismissalView()`. So if `KeyboardRespondable` is kept, it may be less confusing to remove `setupKeyboardRespondable()` from it and have users implement `setupKeyboardDismissalView()` from `KeyboardDismissable`.

**Comment by tylermilner** [comment]
Sure, `setupKeyboardRespondable()` should be fine to remove. I think it might have done more in earlier versions of this library.

**Comment by earlgaspard** [comment]
Fixed with PR #41
